version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports: 
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: notarealpassword
      MONGO_INITDB_DATABASE: mongodb
  
  flaskserver:
    container_name: flaskserver
    build: ./flask_server
    command: flask run 
    volumes: 
      - .:/code
    depends_on: 
      - mongodb
    environment: 
      APP_ENV: "dev"
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_DATABASE: mongodb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: notarealpassword
      MONGODB_HOSTNAME: mongodb

